### ISSUE TITLE
Swagger UI makes requests to 0.0.0.0:3000 instead of 127.0.0.1:3000

### ISSUE THREAD

**Issue by mellkior** [mattddowney/compose-postgrest#6]
Making requests from Swagger results in a network error because the [PostgREST openAPI URI](https://postgrest.org/en/stable/configuration.html#openapi-server-proxy-uri) isn't configured. I'll open a PR with the change I made to get this working locally.

The base URL before the fix:
![image](https://user-images.githubusercontent.com/38818928/149709253-0f5c118d-7f30-4492-ae3c-df01c807208b.png)

The base URL after the fix:
![image](https://user-images.githubusercontent.com/38818928/149709856-0913176e-7e72-4388-9fac-fbc8f904105c.png)

**Comment by mattddowney** [comment]
Thanks for this. Fixed by 51a9c51ac51a60acd1407ad79547aa82ca2a0675
